---
title: Математические методы в зоологии с использованием R
description: Презентации к курсу Математические методы в зоологии с использованием R
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
    theme: flatly
    highlight: haddock
    include:
      after_body: _footer.html
    css: page_styles.css
---
 
## О курсе

### Цель и задачи курса

Цели этого курса: познакомить с применением различных математических методов в биологии (анализ мощности, регрессионный и дисперсионный анализ, анализ главных компонент, многомерное шкалирование, кластерный анализ), и научить самостоятельно анализировать данные с использованием скриптов на языке статистического программирования R, представлять в наглядном виде результаты анализов, интерпретировать их и представлять в виде научного отчета.

### Расписание и контакты

1-я пара по субботам.

Лянгузова Анастасия Дмитриевна -  reinhardtlennon@gmail.com, `@alrbarfkkad` в Телеграм

### Задания, дедлайны и оценки

Тесты по каждой теме (79), 60 баллов за проект (30 --- отчёт в формате `.Rmd`, 30 --- презентация данных). 

Итоговая оценка по результатам выполнения тестов (>50% или 70 баллов зачет, далее баллы будут пересчитаны по системе ECTS). 

$62.0 \le E < 74.4 \le D < 86.8 \le C < 99.2 \le B < 111.6 \le A$


Итоговое количество баллов может измениться, если по ходу курса я добавлю еще задания.

<!--

- [Как и где можно найти помощь с R и статистикой](more_help.html)

-->
